# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Build
      run: |
        npm install && npm run build:local
        
    - uses: jakejarvis/s3-sync-action@master
    
      with:
          args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETKEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: '../../apps/js-python-dart'      # optional: defaults to entire repository  
        DEST_DIR: '/apps/js-python-dart/'    
        
